server:
  port: 8091

app:
  config:
    api-version: v1
    cross-origin: '*' # * 代表所有域名都可以访问
    limit-count: 10 # 每页限制条数
    white-list: 'http://localhost:8080' # 白名单, 不受访问次数限制的 openai
spring:
  datasource:
    username: root
    password: 491300
    url: jdbc:mysql://localhost:3406/openai?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      pool-name: Retail_HikariCP
      minimum-idle: 15
      maximum-pool-size: 25 #连接池最大连接数，默认是10
      auto-commit: true  #此属性控制从池返回的连接的默认自动提交行为,默认值：true
      max-lifetime: 1800000 #此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      connection-timeout: 30000 #数据库连接超时时间,默认30秒，即30000
      connection-test-query: SELECT 1
      idle-timeout: 180000
    type: com.zaxxer.hikari.HikariDataSource
mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml
  config-location: classpath:/mybatis/config/mybatis-config.xml
# 日志
logging:
  level:
    root: info
  config: classpath:logback-spring.xml

# chatGLM-Config
chatglm:
  sdk:
    config:
      enable: true
      api-host: https://open.bigmodel.cn/
      api-secret-key: edb37ef90776015a5b2e3a30c9d7d55a.LTHwEc97IB2luU9l
# 线程池配置
thread:
  pool:
    executor:
      config:
        block-queue-size: 100
        core-pool-size: 20
        max-pool-size: 50
        keep-alive-time: 5000
        policy: CallerRunsPolicy

wx:
  config:
    originalid: gh_0e28293f0408
    appid: wx54cfcf6cc5fca984
    token: kitten

alipay:
  enabled: true
  app_id: 9021000145622833
  merchant_private_key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDE15KWQ+v2E7G+BQqVIAYBM9DM0Z2kpVtgcxaaL3xrYrZzdiG/kgdA4L/iTE048qWy1uaMHpo6yFCCOuJ8Iy7WJWGDeBDEyqqr8fXeKgzoBa9ljZE1FJe1tMmnQyBIpSG8zU4s8+//p1ZsPCWfeE6HpXykFD4yDjymEzfPGdesGr02eZHkO31A49y3Yn2tGLHSVQ6ksAUKubbspYfBgbgGABV1UnHzMC1C5OwxWBy65iXiz0RikO8jFlVt3VejUEIXURbPCFEsIBCpee/OnixjKthUqVlpOYTgv4c4Gfr6+k1rv+K5fGJOs1uR9WnHDnDLHVykab/F4njHeyrSx1TrAgMBAAECggEAN34+yTYk058BwPxS22/HwZcGCngd5Ujo1ewcNyOkA/I0VaC8KvHUMaoq7nVsX92ocR68qEwIVwIaEFzhdPXGQoEPWK0ErTYln4v7MMLSGKdhp1Od2EUR8BwjrY/zDgff1wZaP7oVsxFN//2E7cxQ91TkKq26SwpQdtF8LlquvsnbeECMsc971HDeWzFRW51CbWXu/hKO4U2wILiClyzrwtiAY8EXtAfXJqPPoTwyRdSMirB3aVK6c2OULxoVMM2L9JVHvzGzRAW2EEbcHqXmVRIWHorNG+h4Wv5LidLsj9dLrtMbiAuYHCikKueyWk1zkV+FxYAPZwCMIupI83TEYQKBgQD+PJg+pRBpxm6Xx0nRmWvMpUy9t0/bEwQyfWanZD/ijq6zSy5aPG6RCCfkHe4zGbbIhcl7lRzUop9laKPepeZEGq2L3OMmsG4QjmCMa5jWYVUdcMwRgCu8oR1Y2vBCSwyKLEzJRsn1R6HV3bkKuDl7e13uQdolweBvPbvKFCdfdwKBgQDGNRJqxNi/9ODcy/cFy0/PsLaPuMHq16qicMnjMfp2o9/jIYej603JedMO/T8wJ8TdH+B0lv+NMtgLh1OvCwKeBQvKEP7x+6dw64iBoIM+d2/tworQ4Q0O3X9lSWXu9rTLT22iod/QvMp3FB6z0+tvJepzlKNgDlE/v9zPPAYbLQKBgQCCk6SuKCEx8pTCp7ymRmIzjYLIvenp3u588CNVPgwB1L6tn6OC/R7cpo+2fhjlbgOPIgfFzWQtYgj0ELZ5mEOYHwubliukp2EgZ7/23xx0nzEUGeb15hqQmz9zb5+OrPUX0oDtr8nyjIP2UBbGBrCfV1F7GZ9tXRJkkBRvScKfKQKBgEtrHFPmDPeVjQ5Wyeq5fufvPLgZPChI4dOniRpbBQuptWIuevdDbLjSEx4r/KQtLbpaC8UxQ5INm6lfV9dOIDPShbbgmrGm6QKNjMaONgJJ3hwhH0L1r0tNutDmidPQqeCGm5f7cjdx7rQ6wqf4ZihHzBsonrXJHN9d+P4dv9ENAoGAbw1WUmC3Z8hoMIrAvGaQ6lyADU2D+yWCmIQ+8IlB4ReA3UcH5DA3lLaOLpAGcXhT5e9km2XnAscfyS21QStWFbo7CY1In/EeBgi8K6AeMqxcUVExzk4MHMqYGMsY1KRnsgrfFi6UgZQh67ZUiYQWE3Abfr+wnLx8oew5SWcgSck=
  alipay_public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuKWYjcx2PGXKsf8pJlaUMwT23Gr5fXolsGRm6Lo6cqTUHq6y1+ivfZw3DSC1xmPeuKcOi4JAYGuumExWojEc8i/DTPWqnjPwikNBcf5J6vHGr8WM+qenUvL+Rb43gJZjMcFgsAaKnQYfPIrDW4ysrGPX1PtgWojiPQRCvJNWXHD/9CfS+pqsfFoNwMMVBIFrkB/xNCVMbejG0jHYdnmzm6cXutVy0vr15eihV/WYDB7o5x6+s38br32HAanO0s9dPecvfrjygInTb6USdgNkCwc/nzXeoaxEtPqxasjr90pPVx6GW00lfBI1/Dxp9H/M3pxtAq5sHLduY48uUlwTXQIDAQAB
  notify_url: https://3b2b84e6.r33.cpolar.top/api/v1/sale/pay_notify
  return_url: https://www.thecutekitten.top
  gatewayUrl: https://openapi-sandbox.dl.alipaydev.com/gateway.do