server:
  port: 8091

app:
  config:
    api-version: v1
    cross-origin: '*' # * 代表所有域名都可以访问
    limit-count: 10 # 每页限制条数
spring:
  datasource:
    username: root
    password: 246823579aA
    url: jdbc:mysql://localhost:3306/openai?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      pool-name: Retail_HikariCP
      minimum-idle: 15
      maximum-pool-size: 25 #连接池最大连接数，默认是10
      auto-commit: true  #此属性控制从池返回的连接的默认自动提交行为,默认值：true
      max-lifetime: 1800000 #此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      connection-timeout: 30000 #数据库连接超时时间,默认30秒，即30000
      connection-test-query: SELECT 1
      idle-timeout: 180000
    type: com.zaxxer.hikari.HikariDataSource
mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml
  config-location: classpath:/mybatis/config/mybatis-config.xml
# 日志
logging:
  level:
    root: info
  config: classpath:logback-spring.xml

# chatGLM-Config
chatglm:
  sdk:
    config:
      enable: true
      api-host: https://open.bigmodel.cn/
      api-secret-key: edb37ef90776015a5b2e3a30c9d7d55a.LTHwEc97IB2luU9l
# 线程池配置
thread:
  pool:
    executor:
      config:
        block-queue-size: 100
        core-pool-size: 20
        max-pool-size: 50
        keep-alive-time: 5000
        policy: CallerRunsPolicy